# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vhal_pb2 as vhal__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vhal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPropertyValue = channel.unary_unary(
                '/android.hardware.automotive.vehicle.VehicleService/GetPropertyValue',
                request_serializer=vhal__pb2.GetValueRequest.SerializeToString,
                response_deserializer=vhal__pb2.VehiclePropValue.FromString,
                _registered_method=True)
        self.SetPropertyValue = channel.unary_unary(
                '/android.hardware.automotive.vehicle.VehicleService/SetPropertyValue',
                request_serializer=vhal__pb2.SetValueRequest.SerializeToString,
                response_deserializer=vhal__pb2.Status.FromString,
                _registered_method=True)


class VehicleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPropertyValue(self, request, context):
        """Get a specific property value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPropertyValue(self, request, context):
        """Set a specific property value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPropertyValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyValue,
                    request_deserializer=vhal__pb2.GetValueRequest.FromString,
                    response_serializer=vhal__pb2.VehiclePropValue.SerializeToString,
            ),
            'SetPropertyValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPropertyValue,
                    request_deserializer=vhal__pb2.SetValueRequest.FromString,
                    response_serializer=vhal__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'android.hardware.automotive.vehicle.VehicleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('android.hardware.automotive.vehicle.VehicleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPropertyValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.VehicleService/GetPropertyValue',
            vhal__pb2.GetValueRequest.SerializeToString,
            vhal__pb2.VehiclePropValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPropertyValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.VehicleService/SetPropertyValue',
            vhal__pb2.SetValueRequest.SerializeToString,
            vhal__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
