# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vhal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vhal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvhal.proto\x12#android.hardware.automotive.vehicle\"3\n\x0fGetValueRequest\x12\x0f\n\x07prop_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61rea_id\x18\x02 \x01(\x05\"W\n\x0fSetValueRequest\x12\x44\n\x05value\x18\x01 \x01(\x0b\x32\x35.android.hardware.automotive.vehicle.VehiclePropValue\"\x96\x01\n\x10VehiclePropValue\x12\x0f\n\x07prop_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61rea_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x15\n\x0bint32_value\x18\x04 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x05 \x01(\x02H\x00\x12\x16\n\x0cstring_value\x18\x06 \x01(\tH\x00\x42\x07\n\x05value\"|\n\x06Status\x12>\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x30.android.hardware.automotive.vehicle.Status.Code\"2\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\x0f\n\x0bINVALID_ARG\x10\x01\x12\x11\n\rNOT_AVAILABLE\x10\x02\x32\x88\x02\n\x0eVehicleService\x12\x7f\n\x10GetPropertyValue\x12\x34.android.hardware.automotive.vehicle.GetValueRequest\x1a\x35.android.hardware.automotive.vehicle.VehiclePropValue\x12u\n\x10SetPropertyValue\x12\x34.android.hardware.automotive.vehicle.SetValueRequest\x1a+.android.hardware.automotive.vehicle.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vhal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETVALUEREQUEST']._serialized_start=51
  _globals['_GETVALUEREQUEST']._serialized_end=102
  _globals['_SETVALUEREQUEST']._serialized_start=104
  _globals['_SETVALUEREQUEST']._serialized_end=191
  _globals['_VEHICLEPROPVALUE']._serialized_start=194
  _globals['_VEHICLEPROPVALUE']._serialized_end=344
  _globals['_STATUS']._serialized_start=346
  _globals['_STATUS']._serialized_end=470
  _globals['_STATUS_CODE']._serialized_start=420
  _globals['_STATUS_CODE']._serialized_end=470
  _globals['_VEHICLESERVICE']._serialized_start=473
  _globals['_VEHICLESERVICE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
