# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/DumpResult.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/DumpResult.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4android/hardware/automotive/vehicle/DumpResult.proto\x12)android.hardware.automotive.vehicle.proto\"`\n\nDumpResult\x12 \n\x18\x63\x61ller_should_dump_state\x18\x01 \x01(\x08\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\t\x12 \n\x18refresh_property_configs\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.DumpResult_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUMPRESULT']._serialized_start=99
  _globals['_DUMPRESULT']._serialized_end=195
# @@protoc_insertion_point(module_scope)
