# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/GetMinMaxSupportedValuesTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/GetMinMaxSupportedValuesTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import PropIdAreaId_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_PropIdAreaId__pb2
from android.hardware.automotive.vehicle import RawPropValues_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_RawPropValues__pb2
from android.hardware.automotive.vehicle import StatusCode_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_StatusCode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGandroid/hardware/automotive/vehicle/GetMinMaxSupportedValuesTypes.proto\x12)android.hardware.automotive.vehicle.proto\x1a\x36\x61ndroid/hardware/automotive/vehicle/PropIdAreaId.proto\x1a\x37\x61ndroid/hardware/automotive/vehicle/RawPropValues.proto\x1a\x34\x61ndroid/hardware/automotive/vehicle/StatusCode.proto\"\x91\x02\n\x1aMinMaxSupportedValueResult\x12\x45\n\x06status\x18\x01 \x01(\x0e\x32\x35.android.hardware.automotive.vehicle.proto.StatusCode\x12U\n\x13min_supported_value\x18\x02 \x01(\x0b\x32\x38.android.hardware.automotive.vehicle.proto.RawPropValues\x12U\n\x13max_supported_value\x18\x03 \x01(\x0b\x32\x38.android.hardware.automotive.vehicle.proto.RawPropValues\"s\n\x1fGetMinMaxSupportedValuesRequest\x12P\n\x0fprop_id_area_id\x18\x01 \x03(\x0b\x32\x37.android.hardware.automotive.vehicle.proto.PropIdAreaId\"w\n\x1eGetMinMaxSupportedValuesResult\x12U\n\x06result\x18\x01 \x03(\x0b\x32\x45.android.hardware.automotive.vehicle.proto.MinMaxSupportedValueResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.GetMinMaxSupportedValuesTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MINMAXSUPPORTEDVALUERESULT']._serialized_start=286
  _globals['_MINMAXSUPPORTEDVALUERESULT']._serialized_end=559
  _globals['_GETMINMAXSUPPORTEDVALUESREQUEST']._serialized_start=561
  _globals['_GETMINMAXSUPPORTEDVALUESREQUEST']._serialized_end=676
  _globals['_GETMINMAXSUPPORTEDVALUESRESULT']._serialized_start=678
  _globals['_GETMINMAXSUPPORTEDVALUESRESULT']._serialized_end=797
# @@protoc_insertion_point(module_scope)
