# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/GetSupportedValuesListsTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/GetSupportedValuesListsTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import PropIdAreaId_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_PropIdAreaId__pb2
from android.hardware.automotive.vehicle import RawPropValues_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_RawPropValues__pb2
from android.hardware.automotive.vehicle import StatusCode_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_StatusCode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFandroid/hardware/automotive/vehicle/GetSupportedValuesListsTypes.proto\x12)android.hardware.automotive.vehicle.proto\x1a\x36\x61ndroid/hardware/automotive/vehicle/PropIdAreaId.proto\x1a\x37\x61ndroid/hardware/automotive/vehicle/RawPropValues.proto\x1a\x34\x61ndroid/hardware/automotive/vehicle/StatusCode.proto\"\xbb\x01\n\x19SupportedValuesListResult\x12\x45\n\x06status\x18\x01 \x01(\x0e\x32\x35.android.hardware.automotive.vehicle.proto.StatusCode\x12W\n\x15supported_values_list\x18\x02 \x03(\x0b\x32\x38.android.hardware.automotive.vehicle.proto.RawPropValues\"r\n\x1eGetSupportedValuesListsRequest\x12P\n\x0fprop_id_area_id\x18\x01 \x03(\x0b\x32\x37.android.hardware.automotive.vehicle.proto.PropIdAreaId\"u\n\x1dGetSupportedValuesListsResult\x12T\n\x06result\x18\x01 \x03(\x0b\x32\x44.android.hardware.automotive.vehicle.proto.SupportedValuesListResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.GetSupportedValuesListsTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUPPORTEDVALUESLISTRESULT']._serialized_start=285
  _globals['_SUPPORTEDVALUESLISTRESULT']._serialized_end=472
  _globals['_GETSUPPORTEDVALUESLISTSREQUEST']._serialized_start=474
  _globals['_GETSUPPORTEDVALUESLISTSREQUEST']._serialized_end=588
  _globals['_GETSUPPORTEDVALUESLISTSRESULT']._serialized_start=590
  _globals['_GETSUPPORTEDVALUESLISTSRESULT']._serialized_end=707
# @@protoc_insertion_point(module_scope)
