# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/RawPropValues.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/RawPropValues.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7android/hardware/automotive/vehicle/RawPropValues.proto\x12)android.hardware.automotive.vehicle.proto\"|\n\rRawPropValues\x12\x14\n\x0cint32_values\x18\x01 \x03(\x05\x12\x14\n\x0c\x66loat_values\x18\x02 \x03(\x02\x12\x14\n\x0cint64_values\x18\x03 \x03(\x03\x12\x13\n\x0b\x62yte_values\x18\x04 \x01(\x0c\x12\x14\n\x0cstring_value\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.RawPropValues_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWPROPVALUES']._serialized_start=102
  _globals['_RAWPROPVALUES']._serialized_end=226
# @@protoc_insertion_point(module_scope)
