# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/StatusCode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/StatusCode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4android/hardware/automotive/vehicle/StatusCode.proto\x12)android.hardware.automotive.vehicle.proto\"b\n\x14VehicleHalCallStatus\x12J\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x35.android.hardware.automotive.vehicle.proto.StatusCode*\x82\x02\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\r\n\tTRY_AGAIN\x10\x01\x12\x0f\n\x0bINVALID_ARG\x10\x02\x12\x11\n\rNOT_AVAILABLE\x10\x03\x12\x11\n\rACCESS_DENIED\x10\x04\x12\x12\n\x0eINTERNAL_ERROR\x10\x05\x12\x1a\n\x16NOT_AVAILABLE_DISABLED\x10\x06\x12\x1b\n\x17NOT_AVAILABLE_SPEED_LOW\x10\x07\x12\x1c\n\x18NOT_AVAILABLE_SPEED_HIGH\x10\x08\x12!\n\x1dNOT_AVAILABLE_POOR_VISIBILITY\x10\t\x12\x18\n\x14NOT_AVAILABLE_SAFETY\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.StatusCode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=200
  _globals['_STATUSCODE']._serialized_end=458
  _globals['_VEHICLEHALCALLSTATUS']._serialized_start=99
  _globals['_VEHICLEHALCALLSTATUS']._serialized_end=197
# @@protoc_insertion_point(module_scope)
