# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/SubscribeOptions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/SubscribeOptions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:android/hardware/automotive/vehicle/SubscribeOptions.proto\x12)android.hardware.automotive.vehicle.proto\"\x83\x01\n\x10SubscribeOptions\x12\x0f\n\x07prop_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61rea_ids\x18\x02 \x03(\x05\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x02\x12\x12\n\nresolution\x18\x04 \x01(\x02\x12#\n\x1b\x65nable_variable_update_rate\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.SubscribeOptions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEOPTIONS']._serialized_start=106
  _globals['_SUBSCRIBEOPTIONS']._serialized_end=237
# @@protoc_insertion_point(module_scope)
