# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/SubscribeRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/SubscribeRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import SubscribeOptions_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_SubscribeOptions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:android/hardware/automotive/vehicle/SubscribeRequest.proto\x12)android.hardware.automotive.vehicle.proto\x1a:android/hardware/automotive/vehicle/SubscribeOptions.proto\"`\n\x10SubscribeRequest\x12L\n\x07options\x18\x01 \x01(\x0b\x32;.android.hardware.automotive.vehicle.proto.SubscribeOptionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.SubscribeRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=165
  _globals['_SUBSCRIBEREQUEST']._serialized_end=261
# @@protoc_insertion_point(module_scope)
