# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/SupportedValuesChange.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/SupportedValuesChange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import PropIdAreaId_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_PropIdAreaId__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?android/hardware/automotive/vehicle/SupportedValuesChange.proto\x12)android.hardware.automotive.vehicle.proto\x1a\x36\x61ndroid/hardware/automotive/vehicle/PropIdAreaId.proto\"j\n\x15SupportedValuesChange\x12Q\n\x10prop_id_area_ids\x18\x01 \x03(\x0b\x32\x37.android.hardware.automotive.vehicle.proto.PropIdAreaIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.SupportedValuesChange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUPPORTEDVALUESCHANGE']._serialized_start=166
  _globals['_SUPPORTEDVALUESCHANGE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
