# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/VehicleAreaConfig.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/VehicleAreaConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import VehiclePropertyAccess_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_VehiclePropertyAccess__pb2
from android.hardware.automotive.vehicle import HasSupportedValueInfo_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_HasSupportedValueInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;android/hardware/automotive/vehicle/VehicleAreaConfig.proto\x12)android.hardware.automotive.vehicle.proto\x1a?android/hardware/automotive/vehicle/VehiclePropertyAccess.proto\x1a?android/hardware/automotive/vehicle/HasSupportedValueInfo.proto\"\xb5\x03\n\x11VehicleAreaConfig\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\x05\x12\x17\n\x0fmin_int32_value\x18\x02 \x01(\x05\x12\x17\n\x0fmax_int32_value\x18\x03 \x01(\x05\x12\x17\n\x0fmin_int64_value\x18\x04 \x01(\x03\x12\x17\n\x0fmax_int64_value\x18\x05 \x01(\x03\x12\x17\n\x0fmin_float_value\x18\x06 \x01(\x02\x12\x17\n\x0fmax_float_value\x18\x07 \x01(\x02\x12\x1d\n\x15supported_enum_values\x18\x08 \x03(\x03\x12P\n\x06\x61\x63\x63\x65ss\x18\t \x01(\x0e\x32@.android.hardware.automotive.vehicle.proto.VehiclePropertyAccess\x12$\n\x1csupport_variable_update_rate\x18\n \x01(\x08\x12\x62\n\x18has_supported_value_info\x18\x0b \x01(\x0b\x32@.android.hardware.automotive.vehicle.proto.HasSupportedValueInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.VehicleAreaConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEAREACONFIG']._serialized_start=237
  _globals['_VEHICLEAREACONFIG']._serialized_end=674
# @@protoc_insertion_point(module_scope)
