# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/VehiclePropValueRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/VehiclePropValueRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import StatusCode_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_StatusCode__pb2
from android.hardware.automotive.vehicle import VehiclePropValue_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_VehiclePropValue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAandroid/hardware/automotive/vehicle/VehiclePropValueRequest.proto\x12)android.hardware.automotive.vehicle.proto\x1a\x34\x61ndroid/hardware/automotive/vehicle/StatusCode.proto\x1a:android/hardware/automotive/vehicle/VehiclePropValue.proto\"y\n\x17VehiclePropValueRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12J\n\x05value\x18\x02 \x01(\x0b\x32;.android.hardware.automotive.vehicle.proto.VehiclePropValue\"M\n\x17UpdateSampleRateRequest\x12\x0c\n\x04prop\x18\x01 \x01(\x05\x12\x0f\n\x07\x61rea_id\x18\x02 \x01(\x05\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x02\"k\n\x0eSetValueResult\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x45\n\x06status\x18\x02 \x01(\x0e\x32\x35.android.hardware.automotive.vehicle.proto.StatusCode\"\xb7\x01\n\x0eGetValueResult\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x45\n\x06status\x18\x02 \x01(\x0e\x32\x35.android.hardware.automotive.vehicle.proto.StatusCode\x12J\n\x05value\x18\x03 \x01(\x0b\x32;.android.hardware.automotive.vehicle.proto.VehiclePropValue\"p\n\x18VehiclePropValueRequests\x12T\n\x08requests\x18\x01 \x03(\x0b\x32\x42.android.hardware.automotive.vehicle.proto.VehiclePropValueRequest\"]\n\x0fSetValueResults\x12J\n\x07results\x18\x01 \x03(\x0b\x32\x39.android.hardware.automotive.vehicle.proto.SetValueResult\"]\n\x0fGetValueResults\x12J\n\x07results\x18\x01 \x03(\x0b\x32\x39.android.hardware.automotive.vehicle.proto.GetValueResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.VehiclePropValueRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEPROPVALUEREQUEST']._serialized_start=226
  _globals['_VEHICLEPROPVALUEREQUEST']._serialized_end=347
  _globals['_UPDATESAMPLERATEREQUEST']._serialized_start=349
  _globals['_UPDATESAMPLERATEREQUEST']._serialized_end=426
  _globals['_SETVALUERESULT']._serialized_start=428
  _globals['_SETVALUERESULT']._serialized_end=535
  _globals['_GETVALUERESULT']._serialized_start=538
  _globals['_GETVALUERESULT']._serialized_end=721
  _globals['_VEHICLEPROPVALUEREQUESTS']._serialized_start=723
  _globals['_VEHICLEPROPVALUEREQUESTS']._serialized_end=835
  _globals['_SETVALUERESULTS']._serialized_start=837
  _globals['_SETVALUERESULTS']._serialized_end=930
  _globals['_GETVALUERESULTS']._serialized_start=932
  _globals['_GETVALUERESULTS']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
