# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/VehiclePropConfig.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/VehiclePropConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import VehicleAreaConfig_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_VehicleAreaConfig__pb2
from android.hardware.automotive.vehicle import VehiclePropertyAccess_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_VehiclePropertyAccess__pb2
from android.hardware.automotive.vehicle import VehiclePropertyChangeMode_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_VehiclePropertyChangeMode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;android/hardware/automotive/vehicle/VehiclePropConfig.proto\x12)android.hardware.automotive.vehicle.proto\x1a;android/hardware/automotive/vehicle/VehicleAreaConfig.proto\x1a?android/hardware/automotive/vehicle/VehiclePropertyAccess.proto\x1a\x43\x61ndroid/hardware/automotive/vehicle/VehiclePropertyChangeMode.proto\"\x81\x03\n\x11VehiclePropConfig\x12\x0c\n\x04prop\x18\x01 \x01(\x05\x12P\n\x06\x61\x63\x63\x65ss\x18\x02 \x01(\x0e\x32@.android.hardware.automotive.vehicle.proto.VehiclePropertyAccess\x12Y\n\x0b\x63hange_mode\x18\x03 \x01(\x0e\x32\x44.android.hardware.automotive.vehicle.proto.VehiclePropertyChangeMode\x12R\n\x0c\x61rea_configs\x18\x04 \x03(\x0b\x32<.android.hardware.automotive.vehicle.proto.VehicleAreaConfig\x12\x14\n\x0c\x63onfig_array\x18\x05 \x03(\x05\x12\x15\n\rconfig_string\x18\x06 \x01(\x0c\x12\x17\n\x0fmin_sample_rate\x18\x07 \x01(\x02\x12\x17\n\x0fmax_sample_rate\x18\x08 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.VehiclePropConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEPROPCONFIG']._serialized_start=302
  _globals['_VEHICLEPROPCONFIG']._serialized_end=687
# @@protoc_insertion_point(module_scope)
