# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android/hardware/automotive/vehicle/VehiclePropValue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android/hardware/automotive/vehicle/VehiclePropValue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android.hardware.automotive.vehicle import VehiclePropertyStatus_pb2 as android_dot_hardware_dot_automotive_dot_vehicle_dot_VehiclePropertyStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:android/hardware/automotive/vehicle/VehiclePropValue.proto\x12)android.hardware.automotive.vehicle.proto\x1a?android/hardware/automotive/vehicle/VehiclePropertyStatus.proto\"\x83\x02\n\x10VehiclePropValue\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07\x61rea_id\x18\x02 \x01(\x05\x12\x0c\n\x04prop\x18\x03 \x01(\x05\x12P\n\x06status\x18\x04 \x01(\x0e\x32@.android.hardware.automotive.vehicle.proto.VehiclePropertyStatus\x12\x14\n\x0cint32_values\x18\x05 \x03(\x05\x12\x14\n\x0c\x66loat_values\x18\x06 \x03(\x02\x12\x14\n\x0cint64_values\x18\x07 \x03(\x03\x12\x13\n\x0b\x62yte_values\x18\x08 \x01(\x0c\x12\x14\n\x0cstring_value\x18\t \x01(\t\"`\n\x11VehiclePropValues\x12K\n\x06values\x18\x01 \x03(\x0b\x32;.android.hardware.automotive.vehicle.proto.VehiclePropValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android.hardware.automotive.vehicle.VehiclePropValue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEPROPVALUE']._serialized_start=171
  _globals['_VEHICLEPROPVALUE']._serialized_end=430
  _globals['_VEHICLEPROPVALUES']._serialized_start=432
  _globals['_VEHICLEPROPVALUES']._serialized_end=528
# @@protoc_insertion_point(module_scope)
